categories:
  nszoho:
    label: NS Zoho Settings

  nszoho.general:
    label: Zoho CRM Configuration
    parent: nszoho

settings:
  plugin.tx_nszoho.settings.zohoURL:
    label: Zoho API URL (e.g. https://www.zohoapis.in)
    category: nszoho.general
    type: string
    default: 'https://www.zohoapis.in'

  plugin.tx_nszoho.settings.zohoAccountURL:
    label: Zoho Accounts URL (e.g. https://accounts.zoho.in)
    category: nszoho.general
    type: string
    default: 'https://accounts.zoho.in'

  plugin.tx_nszoho.settings.authtoken:
    label: Auth code / refresh token
    category: nszoho.general
    type: string
    default: ''

  plugin.tx_nszoho.settings.client_id:
    label: Client ID
    category: nszoho.general
    type: string
    default: ''

  plugin.tx_nszoho.settings.client_secret:
    label: Client Secret
    category: nszoho.general
    type: string
    default: ''